const menu = [
  {
    id: 1,
    title: "lasagna",
    category: "lunch",
    price: 15.99,
    img: "./images/lasagna.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "bbq shashlyk",
    category: "dinner",
    price: 23.99,
    img: "./images/bbq.jpg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "burrito",
    category: "lunch",
    price: 11.99,
    img: "./images/burrito.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "eggs with toast",
    category: "breakfast",
    price: 10.99,
    img: "./images/eggs_with_toast.jpg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "french toast",
    category: "breakfast",
    price: 9.99,
    img: "./images/french_toast.jpg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "greek yogurt with berries",
    category: "breakfast",
    price: 11.99,
    img: "./images/greek_yougurt_with_berries.jpg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "hamburger",
    category: "lunch",
    price: 14.99,
    img: "./images/hamburger.jpg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "lasagna",
    category: "dinner",
    price: 16.99,
    img: "./images/lasagna.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "pancakes",
    category: "breakfast",
    price: 8.99,
    img: "./images/pancakes.jpg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: "panini",
    category: "breakfast",
    price: 10.99,
    img: "./images/panini.jpg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 11,
    title: "pizza",
    category: "lunch",
    price: 14.99,
    img: "./images/pizza.jpg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 12,
    title: "salmon with avocado",
    category: "dinner",
    price: 20.99,
    img: "./images/salmon_with_avocado.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 13,
    title: "sandwich",
    category: "breakfast",
    price: 10.99,
    img: "./images/sandwich.jpg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 14,
    title: "steak with fries",
    category: "dinner",
    price: 30.99,
    img: "./images/steak_with_fries.jpg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 15,
    title: "steak",
    category: "dinner",
    price: 28.99,
    img: "./images/steak.jpg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 16,
    title: "tacos",
    category: "lunch",
    price: 14.99,
    img: "./images/tacos.jpg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 17,
    title: "toast with avocado",
    category: "breakfast",
    price: 11.99,
    img: "./images/toast_with_avocado.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 18,
    title: "toast with berries",
    category: "breakfast",
    price: 10.99,
    img: "./images/toast_with_berries.jpg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
